Number1 = float((input('Enter the first number: ')))
Number2 = float((input('Enter the second number: ')))
print(f"Addition: {Number1 + Number2}.") 
print(f"Subtraction: {Number1 - Number2}.")
print(f"Multiplication: {Number1 * Number2}.")
print(f"Division: {Number1 / Number2}.")
print(f"Integer Division: {Number1 // Number2}.")
print(f"Remainder: {Number1 % Number2}.")
print(f"Exponentiation: {Number1 ** Number2}.")